### ISSUE TITLE
User creation specs

### ISSUE THREAD

**Issue by PauuloG** [ZolaApp/zola-api#31]
## User creation

+ [x] First name: Any string (2-35 characters).
+ [x] Last name: Any string (2-35 characters).
+ [x] Job : Any string (2-50 characters).
+ [x] Email : unique (validation for e-mail shape).
+ [x] Password : use zxcvbn to assess password strength. Minimum score shouldn’t be too high.
+ [x] We should also save additional data such as creation/update time (timestamps)

<del>
Email confirmation/activation
</del>

**Comment by Tom-Bonnike** [comment]
Done.
