### ISSUE TITLE
Authentication specs

### ISSUE THREAD

**Issue by PauuloG** [ZolaApp/zola-api#32]
## Authentication

We should have an authentication middleware that handles all login actions and provides the backend with the identity of the user at each request.

Login should be based on a JWT: 
+ [x] When the user successfully logs in, a token should be generated.
    + [x] Move login to a GraphQL mutation
+ [x] By default, tokens don't have any expiration date and are valid for an undefined period of time
+ [x] When the user logs in again, his existing token is served back to him in order to prevent the user having to log in again on all interfaces (when he logs in with the CLI and with the SaaS for example)

<del>However, an option for the user to revoke all active tokens should be provided. That will delete all existing tokens and effectively log the user out of all connected interfaces</del>

+ [x] The middleware should be able to retrieve a user from the token in a way that enables the back-end to treat this user as an instance of the User model.
+ [x] This middleware should be in front of all requests.

**Comment by Tom-Bonnike** [comment]
> However, an option for the user to revoke all active tokens should be provided. That will delete all existing tokens and effectively log the user out of all connected interfaces

Should we simply do that on logout for now? Which means you could only have one session active everywhere. I think that’s fine for security?
Should we store the tokens in redis, too? 😄

**Comment by PauuloG** [comment]
> Should we simply do that on logout for now? Which means you could only have one session active everywhere. I think that’s fine for security?

We could call that action logout, however in the future we should be careful with what we call logout. There should be a difference between the client forgetting about the token (i.e deleting it locally) and the server revoking the token (otherwise we could have confusions and obnoxious disconnections)

> Should we store the tokens in redis, too? 😄

That's a technical choice but I agree :P

**Comment by Tom-Bonnike** [comment]
Guess we could close this @PauuloG?
